; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30145.0 

;include listing.inc

;INCLUDELIB OLDNAMES

EXTRN	__imp_getchar:PROC
EXTRN	__security_check_cookie:PROC
PUBLIC	main
;	COMDAT pdata
;pdata	SEGMENT
;$pdata$main DD	imagerel $LN4
;	DD	imagerel $LN4+17
;	DD	imagerel $unwind$main
;pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
argc$ = 48
argv$ = 56
main	PROC						; COMDAT

; 4    : {

$LN4:
	sub	rsp, 40					; 00000028H

; 5    : 	getchar();

	call	QWORD PTR __imp_getchar

; 6    : 
; 7    : 	return 0;

	xor	eax, eax

; 8    : }

	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
