; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30145.0 

;include listing.inc

;INCLUDELIB OLDNAMES

EXTRN	__security_check_cookie:PROC
PUBLIC	main
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT

; 3    : 	return 0;

	xor	eax, eax

; 4    : }

	ret	0
main	ENDP
_TEXT	ENDS
END
